SUPABASE_URL= "https://qmjykujxwmbacdacyzor.supabase.co"
SUPABASE_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtanlrdWp4d21iYWNkYWN5em9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIwMjM0NDksImV4cCI6MjA0NzU5OTQ0OX0.6TXS63FggRzu88zpU_EFVXU37TJRwn8dYLl48QojuCY"
            